import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React from 'react';
import { useState } from 'react';
import {toast, ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const getStaticProps = async () => {

  const res = await fetch("https://upload-image-api.vercel.app/pictures/");
  const image = await res.json();

  return {
    props: { image },
  };
};
export const deleteImagen = async (id) => {
  try {
    const req = await fetch("https://upload-image-api.vercel.app/pictures/" + id, {
      method: "DELETE",
    });
    const data = await req.json();
    console.log(data);
  } catch (erro) {
    toast.info("Ocorreu um erro!");
  } finally{
    toast.success("Imagem removida com sucesso!");
    setTimeout(()=>{window.location.reload()},5000)
   
  }

}
export const postImagem = async (image, name) => {

  const formData = new FormData()
  formData.append('name', name);
  formData.append('file', image);
  try {
    await fetch("https://upload-image-api.vercel.app/pictures/", {
      method: 'POST',
      body: formData,
    })
  } catch {
    toast.error("Ops! a imagem não foi cadastrada")
  }

};

export default function Home({ image }) {

  const [name_file, setName_file] = useState();
  const [file, setFile] = useState();

  return (
    <>
      <Head>
        <title>Upload</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer autoClose={4000} position={toast.POSITION.BOTTOM_LEFT} />
      <main className={styles.main}>
        <h1>Upload de Imagens</h1>
        <form onSubmit={() => postImagem(file, name_file)}>
          <input type='file' onChange={(e) => { setFile(e.target.files[0]), setName_file(e.target.files[0].name) }}></input>
          <button type='submit'>Enviar</button>
        </form>
        {image.map((img) => (
          <div className={styles.containerImages} key={img._id}>
            <p>Image: {img.name.substring(0, 10)}</p>
            <button onClick={() => deleteImagen(img._id)}>Deletar</button>
            <img className={styles.images} src={`https://upload-image-api.vercel.app/pictures/file/${img._id}`}></img>
          </div>
        ))
        }

      </main>
    </>
  )
}
